In [36]:
import os
import numpy
import tensorflow as tf

os.environ['CUDA_VISIBLE_DEVICES'] = "0"

In [6]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [10]:
# rank one tensor(tensor of a list)
x = tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [11]:
# rank two tensor
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [19]:
x = tf.ones((3,3))
print(x)
x = tf.zeros((3,3))
print(x)
x = tf.eye(3)
print(x)
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.5634007   0.9211462   1.5782915 ]
 [-0.43030596  0.03757949  0.41515028]
 [-0.30904064 -0.43090692 -1.309077  ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.8436868  0.9926549  0.62897944]
 [0.43728054 0.4240402  0.9961895 ]
 [0.8343499  0.83497775 0.10719836]], shape=(3, 3), dtype=float32)


In [18]:
x = tf.range(10)
print(x)
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [21]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y)
print(z)
w = x + y
print(z)
# you can do divide, subtract, multiply

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [23]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.tensordot(x,y,axes=1)

print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [27]:
x = tf.random.normal((2,2))
y = tf.random.normal((2,2))

# matriz multiplication
z = tf.matmul(x,y)

print(z)

w = x @ y

print(z)


tf.Tensor(
[[ 0.2818545  -0.24471712]
 [-0.26753804  0.3069265 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.2818545  -0.24471712]
 [-0.26753804  0.3069265 ]], shape=(2, 2), dtype=float32)


In [28]:
x = tf.constant([[1,2,3,4], [5,6,7,8]])
print(x[0])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [31]:
x = tf.constant([[1,2,3,4], [5,6,7,8]])
print(x[: , 0])
print(x[0 , :])
print(x[0 , 0: 2])
print(x[1 , 2])

tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [33]:
x = tf.random.normal((2,3))
print(x)

x = tf.reshape(x, (3,2))
print(x)

tf.Tensor(
[[ 0.8888097  -0.46402156 -0.17986122]
 [-1.028156   -0.36722696 -0.03713653]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.8888097  -0.46402156]
 [-0.17986122 -1.028156  ]
 [-0.36722696 -0.03713653]], shape=(3, 2), dtype=float32)


In [38]:
x = tf.constant([[1,2,3,4], [5,6,7,8]])
x = x.numpy()
print(x)
x = tf.convert_to_tensor(x)
print(x)

[[1 2 3 4]
 [5 6 7 8]]
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
